apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: istio-system
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      jaeger-infra: query
  template:
    metadata:
      labels:
        app: jaeger
        jaeger-infra: query
    spec:
      containers:
      - name: jaeger-query
        image: jaegertracing/all-in-one:1.50
        args: ["--query.base-path=/"]
        ports:
        - containerPort: 16686
        - containerPort: 16685
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: istio-system
  labels:
    app: jaeger
spec:
  ports:
  - name: http
    port: 16686
    targetPort: 16686
  - name: grpc-query
    port: 16685
    targetPort: 16685
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: tracing
  namespace: istio-system
  labels:
    app: jaeger
spec:
  ports:
  - name: http
    port: 80
    targetPort: 16686
  selector:
    app: jaeger