apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  runtimeClassName: nvidia
  nodeSelector:
    accelerator: nvidia
  containers:
  - name: cuda-vector-add
    image: docker.io/nvidia/cuda:12.2.0-base-ubuntu22.04
    resources:
      limits:
        nvidia.com/gpu: 1
    command: ["nvidia-smi"]
      #command: ["sleep", "infinity"]