apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pytorch
spec:
  runtimeClassName: nvidia
  nodeSelector:
    accelerator: nvidia
  containers:
  - name: pytorch-gpu-test
    image: docker.io/pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
    command: ["bash", "-c"]
    args:
      - |
        apt update && apt install -y wget;
        wget -q https://raw.githubusercontent.com/<YOUR_GITHUB_USERNAME>/gpu-test/main/gpu_test.py -O /gpu_test.py;
        python3 /gpu_test.py
    resources:
      limits:
        nvidia.com/gpu: 1