apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pytorch
spec:
  runtimeClassName: nvidia
  nodeSelector:
    accelerator: nvidia
  containers:
  - name: pytorch-gpu-test
    image: docker.io/pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
    command: ["python3", "/gpu_test.py"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
      - name: gpu-script
        mountPath: /gpu_test.py
        subPath: gpu_test.py
  volumes:
    - name: gpu-script
      configMap:
        name: gpu-script
        items:
        - key: gpu_test.py
          path: gpu_test.py